name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
        bundler-cache: true
    - name: Check for Sass errors
      run: |
        sass --stop-on-error _sass/page.scss _sass/jekyll-theme-cs50.scss
    - name: Check for JS errors
      run: |
        sudo npm install -g acorn
        acorn --silent assets/jekyll-theme-cs50.js
        acorn --silent assets/page.js
