on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: 3.0
    - run: bundle exec jekyll build
    - if: ${{ github.ref == 'refs/heads/demo' }}
      run: |
        cd _site
        git branch --delete --quiet gh-pages || true
        git checkout -b gh-pages
        git add --all --force
        git commit --allow-empty --allow-empty-message
        git push --force origin gh-pages
